 [build] 
     command = "python manage.py collectstatic --noinput" 
     publish = "staticfiles"


[[redirects]]
  from = "/*"
  to = "website/templates/home.html"
  status = 200
  
[dev]
  command = "pip install -r requirements.txt && python manage.py runserver "
